name: Receive LeetCode Stats
on:
  repository_dispatch:
    types: [update_stats]

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - - name: Update stats.json
        run: |
          echo "FMT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          
      - name: Write File
        run: |
          echo '{
            "easy": "${{ github.event.client_payload.easy }}",
            "medium": "${{ github.event.client_payload.medium }}",
            "hard": "${{ github.event.client_payload.hard }}",
            "lastUpdated": "${{ env.FMT_DATE }}"
          }' > src/data/leetcode_stats.json

      - name: Commit and Push changes
        run: |
            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"
            git add src/data/leetcode_stats.json
            # Only commit if there are actual changes to prevent "nothing to commit" errors
            git diff --quiet && git diff --staged --quiet || (git commit -m "Automated LeetCode stats update" && git push)